flowchart LR
  subgraph vlan10["VLAN10 MGMT 10.10.10.0/24"]
    opn[anduin - OPNsense<br/>Protectli FW4C]
    sw[osgiliath - TP-Link TL-SG108E]
  end

  subgraph vlan20["VLAN20 SERVERS 10.10.20.0/24"]
    pve[orthanc - Proxmox Host]
    pal[palantir - LXC<br/>Pi-hole + Unbound]
    minas[minas-tirith - VM/LXC<br/>Grafana + Loki + Promtail + Netdata]
    loth[lothlorien - LXC/VM<br/>UniFi Controller]
    auth[elessar - VM/LXC<br/>Auth & Reverse Proxy]
    riv[rivendell - VM/LXC<br/>Media Docker Host]
  end

  subgraph vlan30["VLAN30 CLIENTS 10.10.30.0/24"]
    clients[Workstations / Phones / iPad]
  end

  subgraph vlan50["VLAN50 IOT 10.10.50.0/24"]
    iot[IoT Devices<br/>HomePods etc.]
  end

  opn --- sw
  sw --- pve
  pve --- pal
  pve --- minas
  pve --- loth
  pve --- riv
  pve --- auth

  clients -->|DNS| pal
  clients -->|Auth| auth
  iot -->|DNS| pal

  riv -->|VPN overlay| gluetun[Gluetun - VPN client]
  gluetun --> qb[qBittorrent]
  gluetun --> arrs[*arr stack<br/>Prowlarr / Sonarr / Radarr etc.]
  riv --> abs[Audiobookshelf]
  riv --> jf[Jellyfin]

